services:
  service-prod:
    container_name: service-prod
    depends_on:
      - db
    env_file: .env
    build:
      target: prod
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./${STATIC_DIR_PATH}:/app/${STATIC_DIR_PATH}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"
    networks:
      - service-prod-net

  service-dev:
    container_name: service-dev
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./${STATIC_DIR_PATH}:/app/${STATIC_DIR_PATH}
    networks:
      - service-dev-net

  db:
    image: postgres:15.3
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgres/data
    networks:
      - service-dev-net
      - service-prod-net


networks:
  service-dev-net:
    name: service-dev-net
    driver: bridge
  service-prod-net:
    name: service-prod-net
    driver: bridge

